### ISSUE TITLE
Gulp Building Error

### ISSUE THREAD

**Issue by arnaumanyosa** [IBMResearch/generator-polymer-init-ibm-application#7]
When running `npm run build` I get this error

```
$ npm run build
> app@0.0.0 build /Users/arm/repositories/app
> gulp build

[12:20:28] Using gulpfile ~/repositories/app/gulpfile.js
[12:20:28] Starting 'build'...
Deleting build directory...
Analyzing build dependencies...
[12:20:28] The following tasks did not complete: build
[12:20:28] Did you forget to signal async completion?

events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/arm/repositories/app/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Users/arm/repositories/app/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Users/arm/repositories/app/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Users/arm/repositories/app/node_modules/gulp-uglify/minifier.js:79:19)
    at DestroyableTransform.Transform._read (/Users/arm/repositories/app/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/arm/repositories/app/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/arm/repositories/app/node_modules/readable-stream/lib/_stream_writable.js:405:64)
    at writeOrBuffer (/Users/arm/repositories/app/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at DestroyableTransform.Writable.write (/Users/arm/repositories/app/node_modules/readable-stream/lib/_stream_writable.js:321:11)
    at Readable.ondata (_stream_readable.js:555:20)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.8.0
npm ERR! npm  v4.0.0
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arm/repositories/app/npm-debug.log
```

**Comment by abdonrd** [comment]
What changes have you made once you have created the project?

Can you share a reproducible demo?

Thanks!

**Comment by arnaumanyosa** [comment]
I created a new dummy project and I added the extra npm and bower packages that I added in my project and it compiles.

Then I copied my src folder from my project to the dummy one and when compiling fails. So te problem is in the code, not the config (gulp, npm, bower settings...)

keep investigating.

**Comment by arnaumanyosa** [comment]
Seems I found the problem. When I change or remove all the `const`, `let` and the `${}` string template, it builds.

So is not compatible with ES6 or I broke some settings?

**Comment by abdonrd** [comment]
No in the default `gulpfile.js`.

But you can compile ES6 to ES5 adding one pipe with [gulp-babel](https://www.npmjs.com/package/gulp-babel) in the `gulpfile.js`.

**Comment by abdonrd** [comment]
Closing :)
